hash-format = "sha256"

[[files]]
file = "FinalFiles/FinalFiles/packwiz-installer.jar"
hash = "c9f646908d340d84773948a9a7d98bc1dae250d35e1016dc6e2b8459760b5598"

[[files]]
file = "FinalFiles/mods/AnvilNeverTooExpensive-fabric-1.21+-1.2.1.jar"
hash = "abf8cf7fe66eab5b2c2ff5cfaad091f1cb73028fb8ffb93f7edef3805bf4a631"

[[files]]
file = "FinalFiles/mods/ArmorStatues-v21.1.0-1.21.1-Fabric.jar"
hash = "9fe18588591728849fcf0c30db470c9213ae1e9c2c0e112efc1dc406bcbf5ab7"

[[files]]
file = "FinalFiles/mods/Clumps-fabric-1.21.1-19.0.0.1.jar"
hash = "49e406cb2872e24a2d2dbe461b93f0c8fbee1748d14c2a941e54f785e3a1e1a7"

[[files]]
file = "FinalFiles/mods/EasyAnvils-v21.1.0-1.21.1-Fabric.jar"
hash = "14e40cafffb4bbe878a3faa59022d0fd2658b5337656cb96f4925d42d10f2f2b"

[[files]]
file = "FinalFiles/mods/EasyMagic-v21.1.4-1.21.1-Fabric.jar"
hash = "14b4837b5ec8cff7e7fdaa8f141498bfae7224a251c987fab77cee7ec55da157"

[[files]]
file = "FinalFiles/mods/EchoChest-v21.1.1-1.21.1-Fabric.jar"
hash = "3f7770fd8ca10c3d0a8768975deffd6a87fcb99cbb1cb1a522aeff9acfc32e02"

[[files]]
file = "FinalFiles/mods/FallingTree-1.21.1-1.21.1.11.jar"
hash = "b07cb3fe67d1f3bb66daf8836373614153790cfaa8c64fadbf53479d1b33cc54"

[[files]]
file = "FinalFiles/mods/ForgeConfigAPIPort-v21.1.6-1.21.1-Fabric.jar"
hash = "2e3a8f0e3bda85a7d722720e7ce879cbd9d028d9395c6fc224d329b3c982d9b1"

[[files]]
file = "FinalFiles/mods/PickUpNotifier-v21.1.1-1.21.1-Fabric.jar"
hash = "9be5ee5fabcf249f59518599c9d0dcd3f748a3e07a1ac553cd53146e17364c01"

[[files]]
file = "FinalFiles/mods/PuzzlesLib-v21.1.39-1.21.1-Fabric.jar"
hash = "67e9b96383a76cb8f011562d67cbd408cca7d85cb199db61cec1704869414fe2"

[[files]]
file = "FinalFiles/mods/RingOfMiner-Fabric-1.21.1-1.7.11.jar"
hash = "e93d1044f20b69b83a2a1151f3e6ca2d691257ca29c02c2ef9a2e11d0d868f73"

[[files]]
file = "FinalFiles/mods/ShoulderSurfing-Fabric-1.21.1-4.15.1.jar"
hash = "1fe0d7064c8efe36ac74aa45181faa7369fd7c25a3f23e7833d5c0681f61e2d2"

[[files]]
file = "FinalFiles/mods/Terrastorage-1.2.7+1.21-1.21.1.jar"
hash = "c0c044067bdb6540605c017149839530d884db3ca0c91ae656f1389e74a57ba3"

[[files]]
file = "FinalFiles/mods/TradingPost-v21.1.1-1.21.1-Fabric.jar"
hash = "5cbf77f55a27e312dd7e56cdc80f2fd7319f2fba8189c69575ff01428d9da4c0"

[[files]]
file = "FinalFiles/mods/VisualWorkbench-v21.1.1-1.21.1-Fabric.jar"
hash = "198e9b3e7a86718354319dadeb26df71cd4d55163f21b826baeb4ccafff54a1d"

[[files]]
file = "FinalFiles/mods/accessories-fabric-1.1.0-beta.52+1.21.1.jar"
hash = "a5e4c69263f529e0c4fb893597f455a7fc7eb5ec98eab5e58e116f52fe1676c4"

[[files]]
file = "FinalFiles/mods/amendments-1.21-2.0.9-fabric.jar"
hash = "d53a763437499ba5b3f9560f8f3436e54f782db5128071df8f0fcfd04694f970"

[[files]]
file = "FinalFiles/mods/appleskin-fabric-mc1.21-3.0.6.jar"
hash = "9a19cec1294b1bc708392a08e6926dcb85d7378ec5ad909a4b6fcb8bc3bfeaa2"

[[files]]
file = "FinalFiles/mods/architectury-13.0.8-fabric.jar"
hash = "10cbbb6f5f96a2f1853b0cc68428424cec8903409517b299ff02350756b6399d"

[[files]]
file = "FinalFiles/mods/artifacts-fabric-13.1.0.jar"
hash = "e74ff7453e374e0bd02fdcddacb913f6fd9fb6c53afa29e7c321b61a8df0d368"

[[files]]
file = "FinalFiles/mods/balm-fabric-1.21.1-21.0.53.jar"
hash = "f34ddaeb29314832e16f1404f928a5a0a66c96e7ff11d5e2fa604657d2116d09"

[[files]]
file = "FinalFiles/mods/c2me-fabric-mc1.21.1-0.3.0+alpha.0.362.jar"
hash = "e1f47def8294fbbd75270e17cbc1bfcfed295049c7daca3d52dd73af2749b296"

[[files]]
file = "FinalFiles/mods/cardinal-components-api-6.1.2.jar"
hash = "10d8c5167cf1c794cda74c5a49279bb087db04749f83651062d594d2a242daa2"

[[files]]
file = "FinalFiles/mods/carryon-fabric-1.21.1-2.2.2.11.jar"
hash = "803d60e5938ad6ec67bdfdf09e6c718eae3265f63e0dbdd2dfdd919c30f5524d"

[[files]]
file = "FinalFiles/mods/chat_heads-0.14.2-fabric-1.21.jar"
hash = "40d0aba503490daf09c855a3e7610b7fb163eef6635fcce5ef7b2c25fda1536e"

[[files]]
file = "FinalFiles/mods/cloth-config-15.0.140-fabric.jar"
hash = "33894e95da3af59014b39d126586d5241e07ea39f8618763e30dab637405f95f"

[[files]]
file = "FinalFiles/mods/coroutil-fabric-1.21.1-1.3.8.jar"
hash = "d4664c92c17ce9608ab4b36f760b2e988ae2de1660d70d746badb3ed5a033e30"

[[files]]
file = "FinalFiles/mods/darksleep-fabric-1.21.1-1.0.1.jar"
hash = "23ecce141f0c34c24e7450959d3ac7c4bc7a786c55f1595668c360e4462a2644"

[[files]]
file = "FinalFiles/mods/disenchanting_table-merged-1.21.1-5.0.2.jar"
hash = "bdb4f294f968b0e5bb75fe4b9bfe65563add01da2e34df81ba6c65fb7e77dc9c"

[[files]]
file = "FinalFiles/mods/doubleslabs-fabric-1.21.1-0.3.0.jar"
hash = "24f0d560169c51a07c81028299bd56d462b86d90f6e7167d55963d4a88930b29"

[[files]]
file = "FinalFiles/mods/fabric-api-0.116.7+1.21.1.jar"
hash = "08018cc48c97415a38016a00dbd5a2c7a460ba6b7a051690a8cb3dbb5e8482a4"

[[files]]
file = "FinalFiles/mods/fence_on_slab-fabric-1.21-1.0.0.jar"
hash = "8f501d3d60fcb18a7d1a3e9f5190b8848acd4a13376d6009f80a68801c27cf21"

[[files]]
file = "FinalFiles/mods/ferritecore-7.0.2-hotfix-fabric.jar"
hash = "e3fae8e321474a35e94f9bb09eafd0440ce0fe98f4aebbc067e392889700a4fa"

[[files]]
file = "FinalFiles/mods/geckolib-fabric-1.21.1-4.8.2.jar"
hash = "a70c334830decbb9d7cb88478a49d19d6ce823ba3356ca62034a445fef3c2d04"

[[files]]
file = "FinalFiles/mods/hole_filler_mod_1.3.0-fabric-mc_1.21.1.jar"
hash = "c0fc2ca7d71b954595d1618227701a8f9c16d2f880506f2d87be96f478d77c04"

[[files]]
file = "FinalFiles/mods/indium-1.0.35+mc1.21.jar"
hash = "13bd78303315ca8f08ea19dfacce8566e152c56615e93a07c490965f390d4ed8"

[[files]]
file = "FinalFiles/mods/ironbookshelves-1.21.1-1.4.11-fabric.jar"
hash = "37fab5a09357a976a687ce9844007f2fc516e1b5f120fdc6cca4e63440b0107f"

[[files]]
file = "FinalFiles/mods/jamlib-fabric-1.3.5+1.21.1.jar"
hash = "889b33cec23db13b4442f934830659a3b0d2e72ca8c481159b94365b6e0968fc"

[[files]]
file = "FinalFiles/mods/jei-1.21.1-fabric-19.25.1.328.jar"
hash = "03fb257a50fa528dff69995cdc1a6ffd0ec61593707ee74342f57e8491b36242"

[[files]]
file = "FinalFiles/mods/journeymap-fabric-1.21.1-6.0.0-beta.52.jar"
hash = "b12b2ee7cd1031c205b5e3ead4ba9f02f1028a97feadd15d36b19c442b0745bc"

[[files]]
file = "FinalFiles/mods/lithium-fabric-0.15.0+mc1.21.1.jar"
hash = "d5fe8d3195eac5b2cdffa00ed7e3077560c64d2064b88221cdea0d9ed05004b6"

[[files]]
file = "FinalFiles/mods/mcw-bridges-3.1.0-mc1.21.1fabric.jar"
hash = "aaa69b2e407c06217fc4dd7485ca7dca840431843e9ae94936748d1d462b18ff"

[[files]]
file = "FinalFiles/mods/mcw-doors-1.1.2-mc1.21.1fabric.jar"
hash = "ca3489587605c2865ea0083cea64cb12e8208c0a7ec024219c215eb57c19e110"

[[files]]
file = "FinalFiles/mods/mcw-furniture-3.4.0-mc1.21.1fabric.jar"
hash = "7b6c2bd8eb3609a04639480911e5db3b5020e252df07f397de8586984a40f121"

[[files]]
file = "FinalFiles/mods/mcw-lights-1.1.2-mc1.21.1fabric.jar"
hash = "20fa8025ffced59d9a83066825f67788163016aa0d39643e023225b42cf57542"

[[files]]
file = "FinalFiles/mods/mcw-mcwholidays-1.1.1-mc1.21.1fabric.jar"
hash = "15c1f5ede47b942f5cb7d4f02c5d16395eecaff3e7304f1a92393e007b3854e0"

[[files]]
file = "FinalFiles/mods/mcw-mcwpaths-1.1.1-mc1.21.1fabric.jar"
hash = "ee1f81f5490bca160ace90749cf98a0513156d82801f4c68af5acf88c90aa898"

[[files]]
file = "FinalFiles/mods/mcw-paintings-1.0.5-1.21.1fabric.jar"
hash = "b153e98f8ae89f3dc9e71055c1964f5500fd87dbb32b155fd83fdb5a49821b9a"

[[files]]
file = "FinalFiles/mods/mcw-stairs-1.0.1-1.21.1fabric.jar"
hash = "fe5f9010213abbdbe128e886b92fe43aa3d1e8b3b96a673c2288ecc2347d9456"

[[files]]
file = "FinalFiles/mods/mcw-windows-2.4.0-1.21.1fabric.jar"
hash = "8a07820ec63e5799cbc24fb67b09b8d1a3fe7b47435568f94999bdcd158defb3"

[[files]]
file = "FinalFiles/mods/mixed-vertical-slabs-fabric-1-21-1.0.0.jar"
hash = "9eeda676d869b70875e8c61c800128debc62efd8bde406f3678af62126507f16"

[[files]]
file = "FinalFiles/mods/monolib-fabric-1.21.1-2.1.0.jar"
hash = "bb3ef8b22386952a38cdecac57073605dd2e7f2f59a8352a3a5d1b5e6c10bec2"

[[files]]
file = "FinalFiles/mods/moonlight-1.21-2.26.5-fabric.jar"
hash = "2c0f1d61d34180a0bf727e2cea656cb6313af4a986ff73c1d875a2325a8e06a5"

[[files]]
file = "FinalFiles/mods/shouldersurfingultimine-1.0.1+1.21.1-fabric.jar"
hash = "ccf27753e4ff4fafafa468aeee252a114e88961d6d44a0acbf9ad3db7ff0e20d"

[[files]]
file = "FinalFiles/mods/sodium-fabric-0.6.13+mc1.21.1.jar"
hash = "e04599514d88e41765f710eeba59e3814909833396bc11b977f48fc2e7e50353"

[[files]]
file = "FinalFiles/mods/spark-1.10.109-fabric.jar"
hash = "fafc121ac53dab1c32e74b7a1cae47d54435ba4cbeeda1180dc96675a7757047"

[[files]]
file = "FinalFiles/mods/supplementaries-1.21-3.4.20-fabric.jar"
hash = "bbfab9a256e3c167e27746b72bb2b4b5683554174464e475a4867260bceceec8"

[[files]]
file = "FinalFiles/mods/trade-cycling-fabric-1.21.1-1.0.18.jar"
hash = "239fb8faaf50dcbf904bd77cd8b7e8b821e98b3352f2cdb9ce4af9043ca0dbbb"

[[files]]
file = "FinalFiles/mods/trashslot-fabric-1.21.1-21.1.4.jar"
hash = "4b06b475c969fd7b49a73035443488b401e71bcaba134470fdeb40d3575600df"

[[files]]
file = "FinalFiles/mods/trinkets-3.10.0.jar"
hash = "349fd2aa8930b232050ee5304db55e4ef738b017971afe7c84acd589a95fda2f"

[[files]]
file = "FinalFiles/mods/u_framework-1.1.0+mc1.21.jar"
hash = "e2191f868a07a07c1cec55571f52a67c2fc6f4459740649ae0119c284f53ddae"

[[files]]
file = "FinalFiles/mods/verticalSlabs-1.1.0.jar"
hash = "b3b2ee51288e8703ec6bf7e8c51e6a91be9952eaafb2f910c81d2c07137e1c56"

[[files]]
file = "FinalFiles/packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"

[[files]]
file = "FinalFiles/packwiz-installer.jar"
hash = "c9f646908d340d84773948a9a7d98bc1dae250d35e1016dc6e2b8459760b5598"

[[files]]
file = "FinalFiles/packwiz.json"
hash = "8a629df54ef1ca7b535a3d0819a61b443205c8eaf439c11fe87dd1e001a27cf3"

[[files]]
file = "FinalFiles/resourcepacks/Bare Bones x Refurbished Furniture.zip"
hash = "af52dad6a2a189992e497068103bf8c98acc69e755f8a6cc625757d5d2f979f2"

[[files]]
file = "FinalFiles/resourcepacks/[Moonsu] Better GUI for T.B. 2.0 1.21.X.zip"
hash = "9065eeaee3676291c7026316f5202b2125707469a8a699e2ca1b451e8ecc987f"

[[files]]
file = "mods/accessories.pw.toml"
hash = "97befad2275e44c557794fbd321b154510279ce7906426607288062e096df86d"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
hash = "b4dd3b4217e0cf479207818b743a38f0566faa947e7b7d0b13c91e1a79d35e3c"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "015053563a1d8ef3334560cd27f8e832935a26a96f151f059f814092b8db50a2"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "d4838d91cd7747816ade0f2f4a46c701a53c3ef84cb278ec24e8f6fb828a85c3"
metafile = true

[[files]]
file = "mods/ante.pw.toml"
hash = "578702da1ba25dfdca3268789021d668105986a63895e731d6ff26d6852488ef"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "39792a11da59cebc770f3918dd0ad53637bcbd206dc19bfa6709392bfd2d1830"
metafile = true

[[files]]
file = "mods/armor-statues.pw.toml"
hash = "73b0a6af0d4be59882d8ae1b0edd62e65c35171277cc9b3082331ad4b6c76850"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "6adae9e2eefad5cf4d1729084860ec6877057dc0a1491d3ce243d7b14fb3d405"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "ddc951666b9b867b0ff7671865a33f15adb5331f3d7c8bc179e0ec86795e020f"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "e1e2cc528cc5bca494254c26e849d6f8f9cb4a1305061ae9c86dcd3d48d4920b"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "1ba7fcf69deeec5536f8c9e43ee4527a5871e9e5805c1801b855e5c00b25d05a"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "2dda36229536c02155b8bdc705598904b74b3e958e56bf7946785f59c3427a9b"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "fe84e2227c405bf9b735f01f307a01768784b9d49df82a13ecda3d3b6d198507"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "74b82158cadd5d72b6f1c706aa7f190c4e791681472fc98735cec30acf622535"
metafile = true

[[files]]
file = "mods/darksleep.pw.toml"
hash = "ce3aea75c10c6590dc2655c3095e1a0fc69ac3adf01793cfb9dffe4a727795d0"
metafile = true

[[files]]
file = "mods/dis-enchanting-table.pw.toml"
hash = "d71851407e388787d67281a0564f357bd6384316fa1e4c1984ac6c549acba68d"
metafile = true

[[files]]
file = "mods/double-slabs.pw.toml"
hash = "549d127b457e9321d0e5265efcdddfb40654592d5225c243ed9a88c643c8fa3e"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "c03848ab316f8f8e07656e08c675541ce90f0ad729d5b31df336fe8f27a58b3f"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "e7a682a577780a52963a998f6941c13cbd75455a65368e9b665c56efca37cbb6"
metafile = true

[[files]]
file = "mods/echo-chest.pw.toml"
hash = "713b1e22a35b604ae56b3b55dd957276bcb611fce663c415b89bdd078f38ac21"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "7d61ad815f97afb27f7e97475e80376aa19fecf25a1b04a500a4c3a6e5055973"
metafile = true

[[files]]
file = "mods/fence_on_slab.pw.toml"
hash = "a47e6471514ccf90ba540452c373e44e65f67f1066aec04f3fe2acf54eb376a9"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/ftb-library-fabric.pw.toml"
hash = "7fd859bf1cc60a0481daf805a8d1955510b1dd1581edc24baaa24e37c4462c83"
metafile = true

[[files]]
file = "mods/ftb-quests-optimizer.pw.toml"
hash = "19f2c6f7f3c370a10d566b560bf9c2ed5c0c68c4eba9fc4d06ef7a5cfa394755"
metafile = true

[[files]]
file = "mods/ftb-ultimine-fabric.pw.toml"
hash = "a22332d16a31ad1b9d83edaec4875ec6363c1329e39bbf1c20964c29d7d70477"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "43419651a1c8ee71281ce6d607fba199f0e87ba41f9725caa65b4dab2e589d49"
metafile = true

[[files]]
file = "mods/hole-filler-mod.pw.toml"
hash = "b4255b08565aabd3720c90390335990e3f84f875588e60c32380a6d67c622d77"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "5f694b0c16bfbf69b05cb28eef7a553ae548e623bc2cbccc98e01d950d3611db"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/iron-bookshelves.pw.toml"
hash = "ab4d1c80575e75ebeb68c14b2aff570070ffe5fb046a2aff776ef51aae4e1c49"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "6e212e9056ddaf5dda18ff6a243c118b1cf839a8ba42b999c594f85751896a33"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "983d9aec075a0c94e1f0f4de901688e8c5aff389be085f21534c3062804d6c70"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "184c5b7f76a47f339f1dcfb8a77e21b4fe0949a0c4a9f3e18ab3ad80af336cb5"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "972db8c2fec6fb2f3545554062d4cd19364778e30d8f079221fe0d459efa8517"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "46e175b662617498d6f250e57f3f66b1b39a40252933b3466e1ff6a7f6209725"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "f5f134844b199b78f07b6f58ded80ee7b6a786d509a95687a2abb48e8dffee6b"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "f48382dc8ad6b473ed5e6d050038513e56697143b1232c1ae8ff40861f06ba2f"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "92cae6a928cbd1d0a232c3ea571d28bdd2112fbf414f7c15bcda71295f07351b"
metafile = true

[[files]]
file = "mods/macaws-holidays.pw.toml"
hash = "07a1c8305abb42f00b4ea3f3470990e0c59275d4a4c450d7d5cb3ad77870a714"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "288747beb2483e473a86de31a9fff544e398d37e661c4a9bb7aa16769f7ee8f5"
metafile = true

[[files]]
file = "mods/macaws-paintings.pw.toml"
hash = "4797458bb275c5e9c3657e353ae598ab38e07e3386092a0c13f27448bef3ddd3"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "1197c76400a13a3961f70538d7acf7764436fc92899cca5bd05b9bf3027601c2"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "b298c392b78418707ae9a32e2cf0af27ea9e57a0a673b895012dc90d08b73157"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "b7efdf14e315ce387de72feb5337e84f96725d6d1c7e4f4cce5d444a75c2da3e"
metafile = true

[[files]]
file = "mods/monolib.pw.toml"
hash = "320a2e1eec379af21e280b2ab039b7e059aa5571101b6862ec0e30d19cf205f5"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "c04b43e6c95e18c7310c97e47b3e5bcf65c23180a899a85c97d9fa8f5f773c98"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "af6de4e48064926264441ace0dc8f3193deedd534e2963c25a7700d4dfa6f825"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "44a6662d6ac604b2173a8bc426a10c0d621c8ba99d37d1b72525c140c42cb358"
metafile = true

[[files]]
file = "mods/ring-of-the-miner.pw.toml"
hash = "05426b07956bf784b273efe6b4b6f12e8bbae4a668f223159e81148cfd68ff5a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "9bdd041fb29ab003ef5bb1f0ba53516847e32e3010a3fce247f743fc98e08a6b"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "d3f1d02d785b5dd6d53ab6b38a903558b36e1e97dfb4e64b76375c75e26e90bb"
metafile = true

[[files]]
file = "mods/terrastorage.pw.toml"
hash = "61b77ade93ba4533ad5bde03ef9277b3b0a7bfe7be1111ef9296df48604f235d"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "3226b1537f8ed0868687b4b537883fbe8cd5311d171e5456a7f1ebb6394e0450"
metafile = true

[[files]]
file = "mods/trading-post.pw.toml"
hash = "cbadc7c7ee3c00babef61035e102dca666e3f75ec94ef2bccb6702cd5811de00"
metafile = true

[[files]]
file = "mods/trashslot.pw.toml"
hash = "40c60c458184ab9d15fdcc4c610607eca60a1557bbf484fad2942a803d75e0ec"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "860812150cb54f0d9ee1bce7b72798b6cc5f752bb05709f0c60231d054ec281d"
metafile = true

[[files]]
file = "mods/unnamed-framework.pw.toml"
hash = "20d3e099a09985abf7aa79d5483c5464f141ef3006987dda0061c53657257a26"
metafile = true

[[files]]
file = "mods/vertical-slabs-xy.pw.toml"
hash = "cdc463b364b1039fad339f27499039148002b47f1bd53a6210355c6997103f4d"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "37c8746fe9057612cd4f21e1221760e8dd2f78ce6b38a237b0ac925de21541e0"
metafile = true

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"

[[files]]
file = "resourcepacks/bare-bones-x-refurbished-furniture.pw.toml"
hash = "49f1ceba2ab4cee196d83aef7d58ddfe49521cf5038c70a2cddd56fd7d89124b"
metafile = true

[[files]]
file = "resourcepacks/moonsu-better-gui-create-style-for-travelers-backpack.pw.toml"
hash = "6b86bc1fe39189965991615ed3fd4fbdc6a3e48d4d70019eec35bc45f0614879"
metafile = true
