hash-format = "sha256"

[[files]]
file = "all-of-te-lights.pw.toml"
hash = "7a4b4e89cdefe23a31d34f7ae52e1e34279fae1078f5fd6b4483db66fdac79a4"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "97befad2275e44c557794fbd321b154510279ce7906426607288062e096df86d"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
hash = "b4dd3b4217e0cf479207818b743a38f0566faa947e7b7d0b13c91e1a79d35e3c"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "015053563a1d8ef3334560cd27f8e832935a26a96f151f059f814092b8db50a2"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "d4838d91cd7747816ade0f2f4a46c701a53c3ef84cb278ec24e8f6fb828a85c3"
metafile = true

[[files]]
file = "mods/ante.pw.toml"
hash = "578702da1ba25dfdca3268789021d668105986a63895e731d6ff26d6852488ef"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "39792a11da59cebc770f3918dd0ad53637bcbd206dc19bfa6709392bfd2d1830"
metafile = true

[[files]]
file = "mods/armor-statues.pw.toml"
hash = "73b0a6af0d4be59882d8ae1b0edd62e65c35171277cc9b3082331ad4b6c76850"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "6adae9e2eefad5cf4d1729084860ec6877057dc0a1491d3ce243d7b14fb3d405"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "ddc951666b9b867b0ff7671865a33f15adb5331f3d7c8bc179e0ec86795e020f"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "5f32244bbf7f4864d6570bde7f7223655f52d5df455e7b9fe650b10dee42f830"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "e1e2cc528cc5bca494254c26e849d6f8f9cb4a1305061ae9c86dcd3d48d4920b"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "1ba7fcf69deeec5536f8c9e43ee4527a5871e9e5805c1801b855e5c00b25d05a"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "2dda36229536c02155b8bdc705598904b74b3e958e56bf7946785f59c3427a9b"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "fe84e2227c405bf9b735f01f307a01768784b9d49df82a13ecda3d3b6d198507"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "74b82158cadd5d72b6f1c706aa7f190c4e791681472fc98735cec30acf622535"
metafile = true

[[files]]
file = "mods/cyberanner-ironchest.pw.toml"
hash = "6a89cf951df2610ceaf07877657de5ae63bf3bc67cc94f5d802c9cc78114fbf9"
metafile = true

[[files]]
file = "mods/darksleep.pw.toml"
hash = "ce3aea75c10c6590dc2655c3095e1a0fc69ac3adf01793cfb9dffe4a727795d0"
metafile = true

[[files]]
file = "mods/dis-enchanting-table.pw.toml"
hash = "d71851407e388787d67281a0564f357bd6384316fa1e4c1984ac6c549acba68d"
metafile = true

[[files]]
file = "mods/double-slabs.pw.toml"
hash = "549d127b457e9321d0e5265efcdddfb40654592d5225c243ed9a88c643c8fa3e"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "c03848ab316f8f8e07656e08c675541ce90f0ad729d5b31df336fe8f27a58b3f"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "e7a682a577780a52963a998f6941c13cbd75455a65368e9b665c56efca37cbb6"
metafile = true

[[files]]
file = "mods/echo-chest.pw.toml"
hash = "713b1e22a35b604ae56b3b55dd957276bcb611fce663c415b89bdd078f38ac21"
metafile = true

[[files]]
file = "mods/enchanted-vertical-slabs.pw.toml"
hash = "c61f4a59a8b5fc28c0c95c47db34c1867f25d0080a06593c41df955e5812f28f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "7d61ad815f97afb27f7e97475e80376aa19fecf25a1b04a500a4c3a6e5055973"
metafile = true

[[files]]
file = "mods/fence_on_slab.pw.toml"
hash = "a47e6471514ccf90ba540452c373e44e65f67f1066aec04f3fe2acf54eb376a9"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "26d58b7f56a90ca889100191dc45705827c0a20ad08771f641e3d4ab42fd4a1d"
metafile = true

[[files]]
file = "mods/ftb-library-fabric.pw.toml"
hash = "7fd859bf1cc60a0481daf805a8d1955510b1dd1581edc24baaa24e37c4462c83"
metafile = true

[[files]]
file = "mods/ftb-quests-optimizer.pw.toml"
hash = "19f2c6f7f3c370a10d566b560bf9c2ed5c0c68c4eba9fc4d06ef7a5cfa394755"
metafile = true

[[files]]
file = "mods/ftb-ultimine-fabric.pw.toml"
hash = "a22332d16a31ad1b9d83edaec4875ec6363c1329e39bbf1c20964c29d7d70477"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "43419651a1c8ee71281ce6d607fba199f0e87ba41f9725caa65b4dab2e589d49"
metafile = true

[[files]]
file = "mods/hole-filler-mod.pw.toml"
hash = "b4255b08565aabd3720c90390335990e3f84f875588e60c32380a6d67c622d77"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "5f694b0c16bfbf69b05cb28eef7a553ae548e623bc2cbccc98e01d950d3611db"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/iron-bookshelves.pw.toml"
hash = "ab4d1c80575e75ebeb68c14b2aff570070ffe5fb046a2aff776ef51aae4e1c49"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "6e212e9056ddaf5dda18ff6a243c118b1cf839a8ba42b999c594f85751896a33"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "983d9aec075a0c94e1f0f4de901688e8c5aff389be085f21534c3062804d6c70"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "184c5b7f76a47f339f1dcfb8a77e21b4fe0949a0c4a9f3e18ab3ad80af336cb5"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "972db8c2fec6fb2f3545554062d4cd19364778e30d8f079221fe0d459efa8517"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "46e175b662617498d6f250e57f3f66b1b39a40252933b3466e1ff6a7f6209725"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "f5f134844b199b78f07b6f58ded80ee7b6a786d509a95687a2abb48e8dffee6b"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "f48382dc8ad6b473ed5e6d050038513e56697143b1232c1ae8ff40861f06ba2f"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "92cae6a928cbd1d0a232c3ea571d28bdd2112fbf414f7c15bcda71295f07351b"
metafile = true

[[files]]
file = "mods/macaws-holidays.pw.toml"
hash = "07a1c8305abb42f00b4ea3f3470990e0c59275d4a4c450d7d5cb3ad77870a714"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "288747beb2483e473a86de31a9fff544e398d37e661c4a9bb7aa16769f7ee8f5"
metafile = true

[[files]]
file = "mods/macaws-paintings.pw.toml"
hash = "4797458bb275c5e9c3657e353ae598ab38e07e3386092a0c13f27448bef3ddd3"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "1197c76400a13a3961f70538d7acf7764436fc92899cca5bd05b9bf3027601c2"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "b298c392b78418707ae9a32e2cf0af27ea9e57a0a673b895012dc90d08b73157"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "b7efdf14e315ce387de72feb5337e84f96725d6d1c7e4f4cce5d444a75c2da3e"
metafile = true

[[files]]
file = "mods/monolib.pw.toml"
hash = "320a2e1eec379af21e280b2ab039b7e059aa5571101b6862ec0e30d19cf205f5"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "c04b43e6c95e18c7310c97e47b3e5bcf65c23180a899a85c97d9fa8f5f773c98"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "af6de4e48064926264441ace0dc8f3193deedd534e2963c25a7700d4dfa6f825"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "44a6662d6ac604b2173a8bc426a10c0d621c8ba99d37d1b72525c140c42cb358"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "7ceada6e6fdfb868c17a2d2212cb3b494150fa5717d653605464176f3e4c65de"
metafile = true

[[files]]
file = "mods/ring-of-the-enderchest-fabric.pw.toml"
hash = "02e36c927b764dd9f70e72983e052488854ee02045a94a6c34df30616748d191"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "9bdd041fb29ab003ef5bb1f0ba53516847e32e3010a3fce247f743fc98e08a6b"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "d3f1d02d785b5dd6d53ab6b38a903558b36e1e97dfb4e64b76375c75e26e90bb"
metafile = true

[[files]]
file = "mods/terrastorage.pw.toml"
hash = "61b77ade93ba4533ad5bde03ef9277b3b0a7bfe7be1111ef9296df48604f235d"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "3226b1537f8ed0868687b4b537883fbe8cd5311d171e5456a7f1ebb6394e0450"
metafile = true

[[files]]
file = "mods/trading-post.pw.toml"
hash = "cbadc7c7ee3c00babef61035e102dca666e3f75ec94ef2bccb6702cd5811de00"
metafile = true

[[files]]
file = "mods/trashslot.pw.toml"
hash = "40c60c458184ab9d15fdcc4c610607eca60a1557bbf484fad2942a803d75e0ec"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "fb543e76311a6ae078aa9e5b56c93c2a3b3fba34900809d024c61900db3acf2e"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "860812150cb54f0d9ee1bce7b72798b6cc5f752bb05709f0c60231d054ec281d"
metafile = true

[[files]]
file = "mods/unnamed-framework.pw.toml"
hash = "20d3e099a09985abf7aa79d5483c5464f141ef3006987dda0061c53657257a26"
metafile = true

[[files]]
file = "mods/vertical-slabs-xy.pw.toml"
hash = "cdc463b364b1039fad339f27499039148002b47f1bd53a6210355c6997103f4d"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "37c8746fe9057612cd4f21e1221760e8dd2f78ce6b38a237b0ac925de21541e0"
metafile = true

[[files]]
file = "resourcepacks/bare-bones-x-refurbished-furniture.pw.toml"
hash = "49f1ceba2ab4cee196d83aef7d58ddfe49521cf5038c70a2cddd56fd7d89124b"
metafile = true

[[files]]
file = "resourcepacks/moonsu-better-gui-create-style-for-travelers-backpack.pw.toml"
hash = "6b86bc1fe39189965991615ed3fd4fbdc6a3e48d4d70019eec35bc45f0614879"
metafile = true
