name = "y"
author = "YahiaH"
version = "y"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "734bec7fcade9b1a180ed1c8fce18333bc214770a0bec2f143d27d4f0db95f16"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"
